
import React from 'react';
import { Card } from './common/Card';
import { NexusLogo } from './Icons';

const Article: React.FC<{ number: number; title: string; children: React.ReactNode }> = ({ number, title, children }) => (
    <Card className="mb-6 border-transparent bg-slate-900/50">
        <div className="p-6">
            <h3 className="text-xl font-bold text-cyan-400 mb-4">
                <span className="font-mono text-gray-500 mr-3">§{number}</span>{title}
            </h3>
            <div className="prose prose-invert max-w-none text-gray-400 text-sm leading-relaxed space-y-3 pl-8">
                {children}
            </div>
        </div>
    </Card>
);

export const Compliance: React.FC = () => {
    return (
        <div className="p-4 md:p-8 overflow-y-auto h-full bg-slate-800 text-gray-300">
            <div className="max-w-5xl mx-auto">
                <header className="text-center mb-12">
                     <NexusLogo className="w-16 h-16 text-nexus-blue mx-auto mb-4" />
                    <h2 className="text-3xl font-bold mb-2 text-center text-gray-100 tracking-tight">BWGA Nexus™ Platform: Terms of Service & Ethical Use Policy</h2>
                    <p className="text-lg text-gray-400">Version 2.0</p>
                </header>

                <p className="text-center text-gray-400 mb-8 italic">Please read these terms carefully. They govern your access to and use of the BWGA Nexus AI platform and constitute a binding legal agreement between you and BW Global Advisory.</p>

                <Article number={1} title="Acceptance of Terms & Service Description">
                    <p>
                        By accessing or using the BWGA Nexus™ platform, including any reports, data, or interactive features ("Service"), you agree to be bound by these Terms of Service & Ethical Use Policy ("Terms").
                    </p>
                    <p>
                        The Service is an AI-powered strategic intelligence tool in a continuous <strong className="text-amber-300">Research & Development (R&D)</strong> phase. It is designed to provide preliminary, high-level analysis to bridge the "Global Understanding Gap" for regional economic development. Features, pricing (currently free for R&D), and methodologies may change.
                    </p>
                </Article>
                
                <Article number={2} title="AI-Generated Content, Methodology & Limitations">
                    <p>
                        You acknowledge that all reports and analyses ("Content") are generated by the BWGA Nexus AI engine. This proprietary system integrates advanced AI models with a specialized analytical framework built on established regional science principles. To source real-time data points, the engine utilizes Google Search, but its core value lies in the subsequent application of our proprietary methodologies and the Nexus Symbiotic Intelligence Language (NSIL).
                    </p>
                    <p>
                        Despite this sophistication, the Content is subject to the following fundamental limitations:
                    </p>
                     <ul className="list-disc list-outside space-y-2">
                         <li><strong className="text-white">A Tool for Preliminary Analysis:</strong> The Service is designed as a powerful informational tool for initial discovery and strategic brainstorming. It is not a substitute for formal due diligence, legal counsel, or certified financial and investment advice.</li>
                         <li><strong className="text-white">Verification is Mandatory:</strong> AI models can produce inaccurate, incomplete, or outdated information. All data, analysis, and conclusions presented in the Content must be independently verified by you before any binding decisions are made.</li>
                         <li><strong className="text-white">No Guarantees or Warranties:</strong> BWGA makes no guarantees or warranties, express or implied, regarding the accuracy, completeness, reliability, or suitability of the information provided. All business, investment, and strategic outcomes resulting from the use of the Content are solely your responsibility.</li>
                         <li><strong className="text-white">Dynamic R&D Environment:</strong> The underlying AI models, methodologies, and data sources are part of a continuous Research & Development process and may be updated, changed, or refined without notice.</li>
                     </ul>
                </Article>

                <Article number={3} title="User Obligations and Responsible Use">
                    <p>
                        As a user, you agree to:
                    </p>
                     <ul className="list-disc list-outside space-y-2">
                        <li>Provide accurate and lawful information when prompted (e.g., your name, department, strategic objectives).</li>
                        <li>Assume full responsibility for any decisions, actions, or outcomes resulting from your use of the Service.</li>
                        <li>Conduct your own comprehensive due diligence before making any commitment based on information from the Service.</li>
                        <li>Use the Service in a professional and ethical manner, consistent with its intended purpose of fostering positive economic development.</li>
                     </ul>
                </Article>
                
                <Article number={4} title="Confidentiality & Data Privacy">
                    <p>
                        We are committed to protecting your strategic interests.
                    </p>
                    <ul className="list-disc list-outside space-y-2">
                        <li><strong className="text-white">Query Confidentiality:</strong> Your specific identity, company name, and the detailed "Strategic Intent" you provide are treated as strictly confidential. This information is used to generate your report but is not shared with third parties without your explicit consent.</li>
                        <li><strong className="text-white">The Proactive Match System:</strong> By generating a report, you acknowledge that your <strong className="text-amber-300">anonymized interest</strong> (e.g., "A UK-based FinTech firm is exploring opportunities in Southeast Asia") may be logged. If a compatible, reciprocal interest is registered by another party, BWGA may propose a formal, consent-based introduction. Your identity will never be revealed unless you agree to this introduction.</li>
                        <li><strong className="text-white">Data Use for Improvement:</strong> Anonymized and aggregated data may be used to train and improve the core Nexus AI engine and its underlying methodologies.</li>
                    </ul>
                </Article>

                <Article number={5} title="Prohibited Conduct">
                    <p>
                       You are expressly prohibited from using the Service for any of the following purposes:
                    </p>
                     <ul className="list-disc list-outside space-y-2">
                        <li>Any unlawful activity, including but not limited to activities that violate local, national, or international laws or sanctions.</li>
                        <li>Scraping, data mining, reverse-engineering, or attempting to replicate the Service's proprietary methodologies or the Nexus Symbiotic Intelligence Language (NSIL).</li>
                        <li>Reselling, sublicensing, or otherwise commercializing reports or data from the Service without prior written consent from BWGA.</li>
                        <li>Introducing malicious software or using the service in a way that could disable, overburden, or impair its functioning.</li>
                    </ul>
                </Article>

                <Article number={6} title="Intellectual Property">
                    <p>The concepts, methodologies, analytical processes, platform architecture, the "Nexus Symbiotic Intelligence Language" (NSIL), and the "BWGA Nexus™" name and system constitute the developing and proprietary intellectual property of BW Global Advisory (Brayden Walls, ABN 55 978 113 300). All rights are reserved.</p>
                    <p className="font-semibold text-rose-300">All information, analysis, and data disclosed by BWGA is provided to recipients on a STRICTLY CONFIDENTIAL BASIS and is for internal evaluation purposes only.</p>
                </Article>

                <Article number={7} title="Disclaimer of Warranties & Limitation of Liability">
                    <p>
                        THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. BWGA DISCLAIMS ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
                    </p>
                    <p>
                        TO THE FULLEST EXTENT PERMITTED BY LAW, BW GLOBAL ADVISORY SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM (A) YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE SERVICE; (B) ANY CONDUCT OR CONTENT OF ANY THIRD PARTY ON THE SERVICE; OR (C) UNAUTHORIZED ACCESS, USE, OR ALTERATION OF YOUR TRANSMISSIONS OR CONTENT.
                    </p>
                </Article>

                <Article number={8} title="Governing Law & Modifications">
                    <p>
                        These Terms shall be governed by the laws of the jurisdiction in which BW Global Advisory is registered, without regard to its conflict of law provisions.
                    </p>
                    <p>
                        BWGA reserves the right to modify these Terms at any time. We will provide notice of material changes. Your continued use of the Service after any such changes constitutes your acceptance of the new Terms.
                    </p>
                </Article>

                 <div className="text-center mt-12 text-gray-500">
                    <p>For questions about these terms, please contact BW Global Advisory.</p>
                    <p>Your use of the BWGA Nexus AI platform signifies your agreement to this policy.</p>
                </div>
            </div>
        </div>
    );
};
